name: Python CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: ['core', 'needle', 'doc']

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Firefox 65
      run: |
        sudo apt-get purge firefox
        wget "https://ftp.mozilla.org/pub/firefox/releases/65.0.1/linux-x86_64/en-US/firefox-65.0.1.tar.bz2"
        tar -xjf firefox-65.0.1.tar.bz2
        sudo mv firefox /opt/firefox
        sudo ln -s /opt/firefox/firefox /usr/bin/firefox

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - uses: browser-actions/setup-geckodriver@latest
    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
        BOKCHOY_HEADLESS: true
      run: tox

    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='core'
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        fail_ci_if_error: true
